In [ ]:
import numpy as np

In [ ]:
#1
import pandas as pd

data = {"name": ["Strom, Mrs. Wilhelm (Elna Matilda Persson)", "Navratil, Mr. Michel (Louis M Hoffman)", "Minahan, Miss. Daisy E"],
        "age": [29, 36.5, 33],
        "sex": ["female", "male", "female"]}

my_df = pd.DataFrame(data)

my_df

                                         name   age     sex
0  Strom, Mrs. Wilhelm (Elna Matilda Persson)  29.0  female
1      Navratil, Mr. Michel (Louis M Hoffman)  36.5    male
2                      Minahan, Miss. Daisy E  33.0  female

In [ ]:
#2
titanic_df = pd.read_csv('../content/sample_data/titanic_csv.csv')
titanic_df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
454,1,1,Goldenberg,Mr. Samuel L,male,49.0,1,0,17453,89.1042,C92,C
234,1,3,Asplund,Miss. Lillian Gertrud,female,5.0,4,2,347077,31.3875,NaN,S
556,0,1,Wright,Mr. George,male,62.0,0,0,113807,26.55,NaN,S
766,1,1,Hogeboom,Mrs. John C (Anna Andrews),female,51.0,1,0,13502,77.9583,D11,S
444,1,2,Reynaldo,Ms. Encarnacion,female,28.0,0,0,230434,13.0,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
363,0,3,Barbara,Mrs. (Catherine David),female,45.0,0,1,2691,14.4542,NaN,C
447,1,2,Mellinger,Miss. Madeleine Violet,female,13.0,0,1,250644,19.5,NaN,S
95,0,3,Coxon,Mr. Daniel,male,59.0,0,0,364500,7.25,NaN,S
59,1,2,West,Miss. Constance Mirium,female,5.0,1,2,C.A. 34651,27.75,NaN,S
33,1,3,Glynn,Miss. Mary Agatha,female,NaN,0,0,335677,7.75,NaN,Q

In [ ]:
titanic_df = titanic_df.rename (
    columns = {
        'PassengerId': 'passengerid', 'Survived': 'survived', 'Pclass': 'pclass', 'Name': 'name', 'Sex': 'sex',
       'Age': 'age', 'SibSp': 'sibsp', 'Parch': 'parch', 'Ticket': 'ticket',
       'Fare': 'fare', 'Cabin': 'cabin', 'Embarked': 'embarked'
    }
)

In [ ]:
#3
gist_df = pd.read_csv('https://gist.githubusercontent.com/zaryanezrya/8b4ef51c707cb16d5e88a44dc00a1bb2/raw/41230f49c6268e072dbf102672f670be256922ab/gistfile1.txt')
gist_df

,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
0,552,0,2,"Sharp, Mr. Percival James R",male,27.0,0,0,244358,26.0000,NaN,S
1,689,0,3,"Fischer, Mr. Eberhard Thelander",male,18.0,0,0,350036,7.7958,NaN,S
2,605,1,1,"Homer, Mr. Harry (""Mr E Haven"")",male,35.0,0,0,111426,26.5500,NaN,C
3,305,0,3,"Williams, Mr. Howard Hugh ""Harry""",male,NaN,0,0,A/5 2466,8.0500,NaN,S
4,290,1,3,"Connolly, Miss. Kate",female,22.0,0,0,370373,7.7500,NaN,Q
...,...,...,...,...,...,...,...,...,...,...,...,...
495,482,0,2,"Frost, Mr. Anthony Wood ""Archie""",male,NaN,0,0,239854,0.0000,NaN,S
496,155,0,3,"Olsen, Mr. Ole Martin",male,NaN,0,0,Fa 265302,7.3125,NaN,S
497,851,0,3,"Andersson, Master. Sigvard Harald Elias",male,4.0,4,2,347082,31.2750,NaN,S
498,850,1,1,"Goldenberg, Mrs. Samuel L (Edwiga Grabowska)",female,NaN,1,0,17453,89.1042,C92,C
499,77,0,3,"Staneff, Mr. Ivan",male,NaN,0,0,349208,7.8958,NaN,S

In [ ]:
#4
combined_df = pd.concat([titanic_df, gist_df])

combined_df = combined_df.drop_duplicates()
combined_df

,passengerid,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
454,1,1,Goldenberg,Mr. Samuel L,male,49.0,1,0,17453,89.1042,C92,C
234,1,3,Asplund,Miss. Lillian Gertrud,female,5.0,4,2,347077,31.3875,NaN,S
556,0,1,Wright,Mr. George,male,62.0,0,0,113807,26.55,NaN,S
766,1,1,Hogeboom,Mrs. John C (Anna Andrews),female,51.0,1,0,13502,77.9583,D11,S
444,1,2,Reynaldo,Ms. Encarnacion,female,28.0,0,0,230434,13.0,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
495,482,0,2,"Frost, Mr. Anthony Wood ""Archie""",male,NaN,0,0,239854,0.0,NaN,S
496,155,0,3,"Olsen, Mr. Ole Martin",male,NaN,0,0,Fa 265302,7.3125,NaN,S
497,851,0,3,"Andersson, Master. Sigvard Harald Elias",male,4.0,4,2,347082,31.275,NaN,S
498,850,1,1,"Goldenberg, Mrs. Samuel L (Edwiga Grabowska)",female,NaN,1,0,17453,89.1042,C92,C
499,77,0,3,"Staneff, Mr. Ivan",male,NaN,0,0,349208,7.8958,NaN,S

In [ ]:
#5
combined_df = combined_df.set_index('passengerid')

combined_df = combined_df.sort_index()
combined_df

,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
passengerid,,,,,,,,,,,
0,3,Patchett,Mr. George,male,19.0,0,0,358585,14.5,NaN,S
0,3,Emir,Mr. Farred Chehab,male,NaN,0,0,2631,7.225,NaN,C
0,3,Holm,Mr. John Fredrik Alexander,male,43.0,0,0,C 7075,6.45,NaN,S
0,2,Laroche,Mr. Joseph Philippe Lemercier,male,25.0,1,2,SC/Paris 2123,41.5792,NaN,C
0,3,Allum,Mr. Owen George,male,18.0,0,0,2223,8.3,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0,NaN,S
888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0,B42,S
889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0,C148,C
891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [ ]:
#6
combined_df.info()

combined_df.describe()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 991 entries, 0 to 891
Data columns (total 11 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   survived  991 non-null    int64
 1   pclass    991 non-null    object
 2   name      991 non-null    object
 3   sex       983 non-null    object
 4   age       809 non-null    float64
 5   sibsp     991 non-null    int64
 6   parch     991 non-null    object
 7   ticket    991 non-null    object
 8   fare      974 non-null    object
 9   cabin     247 non-null    object
 10  embarked  967 non-null    object
dtypes: float64(1), int64(2), object(8)
memory usage: 92.9+ KB

         survived         age       sibsp
count  991.000000  809.000000  991.000000
mean     1.316852   29.098690    0.515641
std      1.188543   15.154537    1.080361
min      0.000000    0.000000    0.000000
25%      0.000000   20.000000    0.000000
50%      1.000000   28.000000    0.000000
75%      3.000000   38.000000    1.000000
max      3.000000   80.000000    8.000000

In [ ]:
#7
combined_df.iloc[0], combined_df.iloc[2] = combined_df.iloc[2].copy(), combined_df.iloc[0].copy()

In [ ]:
#8
combined_df['sex'] = combined_df['sex'].map({'female': 'f', 'male': 'm'})
combined_df

,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked
passengerid,,,,,,,,,,,
0,3,Holm,Mr. John Fredrik Alexander,m,43.0,0,0,C 7075,6.45,NaN,S
0,3,Emir,Mr. Farred Chehab,m,NaN,0,0,2631,7.225,NaN,C
0,3,Patchett,Mr. George,m,19.0,0,0,358585,14.5,NaN,S
0,2,Laroche,Mr. Joseph Philippe Lemercier,m,25.0,1,2,SC/Paris 2123,41.5792,NaN,C
0,3,Allum,Mr. Owen George,m,18.0,0,0,2223,8.3,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...
887,0,2,"Montvila, Rev. Juozas",m,27.0,0,0,211536,13.0,NaN,S
888,1,1,"Graham, Miss. Margaret Edith",f,19.0,0,0,112053,30.0,B42,S
889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",f,NaN,1,2,W./C. 6607,23.45,NaN,S
890,1,1,"Behr, Mr. Karl Howell",m,26.0,0,0,111369,30.0,C148,C
891,0,3,"Dooley, Mr. Patrick",m,32.0,0,0,370376,7.75,NaN,Q

In [ ]:
#9
grouped = combined_df.groupby('ticket').count()

result = grouped[grouped['name'] >= 6]['name']
print(result)

ticket
1601            8
17421           6
3101295         6
347082          8
347088          9
CA 2144         6
CA. 2343        7
S.O.C. 14879    6
Name: name, dtype: int64

In [ ]:
#10
merged_df = combined_df.merge(my_df, on='name', how='inner')

common_cabins = merged_df['cabin'].unique()

people_in_common_cabins = combined_df[combined_df['cabin'].isin(common_cabins)]
people_in_common_cabins[['name', 'cabin']]

                                                          name cabin
passengerid
11                             Sandstrom, Miss. Marguerite Rut    G6
206                                 Strom, Miss. Telma Matilda    G6
252                 Strom, Mrs. Wilhelm (Elna Matilda Persson)    G6
395          Sandstrom, Mrs. Hjalmar (Agnes Charlotta Bengt...    G6

In [ ]:
#11
combined_df['birthyear'] = 1912  - combined_df['age']
combined_df

,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,birthyear
passengerid,,,,,,,,,,,,
0,3,Holm,Mr. John Fredrik Alexander,m,43.0,0,0,C 7075,6.45,NaN,S,1869.0
0,3,Emir,Mr. Farred Chehab,m,NaN,0,0,2631,7.225,NaN,C,NaN
0,3,Patchett,Mr. George,m,19.0,0,0,358585,14.5,NaN,S,1893.0
0,2,Laroche,Mr. Joseph Philippe Lemercier,m,25.0,1,2,SC/Paris 2123,41.5792,NaN,C,1887.0
0,3,Allum,Mr. Owen George,m,18.0,0,0,2223,8.3,NaN,S,1894.0
...,...,...,...,...,...,...,...,...,...,...,...,...
887,0,2,"Montvila, Rev. Juozas",m,27.0,0,0,211536,13.0,NaN,S,1885.0
888,1,1,"Graham, Miss. Margaret Edith",f,19.0,0,0,112053,30.0,B42,S,1893.0
889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",f,NaN,1,2,W./C. 6607,23.45,NaN,S,NaN
890,1,1,"Behr, Mr. Karl Howell",m,26.0,0,0,111369,30.0,C148,C,1886.0
891,0,3,"Dooley, Mr. Patrick",m,32.0,0,0,370376,7.75,NaN,Q,1880.0

In [ ]:
#12
combined_df['сompanion'] = combined_df.groupby('cabin')['cabin'].transform('count') - 1

combined_df['сompanion'].fillna(0, inplace=True)
combined_df

,survived,pclass,name,sex,age,sibsp,parch,ticket,fare,cabin,embarked,birthyear,сompanion
passengerid,,,,,,,,,,,,,
0,3,Holm,Mr. John Fredrik Alexander,m,43.0,0,0,C 7075,6.45,NaN,S,1869.0,0.0
0,3,Emir,Mr. Farred Chehab,m,NaN,0,0,2631,7.225,NaN,C,NaN,0.0
0,3,Patchett,Mr. George,m,19.0,0,0,358585,14.5,NaN,S,1893.0,0.0
0,2,Laroche,Mr. Joseph Philippe Lemercier,m,25.0,1,2,SC/Paris 2123,41.5792,NaN,C,1887.0,0.0
0,3,Allum,Mr. Owen George,m,18.0,0,0,2223,8.3,NaN,S,1894.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
887,0,2,"Montvila, Rev. Juozas",m,27.0,0,0,211536,13.0,NaN,S,1885.0,0.0
888,1,1,"Graham, Miss. Margaret Edith",f,19.0,0,0,112053,30.0,B42,S,1893.0,0.0
889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",f,NaN,1,2,W./C. 6607,23.45,NaN,S,NaN,0.0
890,1,1,"Behr, Mr. Karl Howell",m,26.0,0,0,111369,30.0,C148,C,1886.0,0.0
891,0,3,"Dooley, Mr. Patrick",m,32.0,0,0,370376,7.75,NaN,Q,1880.0,0.0

In [ ]:
#13
indices = combined_df[combined_df.index == 1].index

if len(indices) > 1:
    combined_df.iloc[0], combined_df.iloc[indices[0]] = combined_df.iloc[indices[0]].copy(), combined_df.iloc[0].copy()

In [ ]:
#14
combined_df.to_csv('../content/sample_data/output.csv')

In [ ]:
#15
combined_df['fare'] = pd.to_numeric(combined_df['fare'], errors='coerce')

combined_df = combined_df.dropna(subset=['fare'])

top_10_passengers = combined_df.sort_values(by='fare', ascending=False).head(10)
top_10_passengers[['name', 'fare']]

                                                        name      fare
passengerid
1                                  Mr. Thomas Drake Martinez  512.3292
1                                                 Miss. Anna  512.3292
1                                              Mr. Gustave J  512.3292
1                                          Miss. Mabel Helen  263.0000
342                           Fortune, Miss. Alice Elizabeth  263.0000
28                            Fortune, Mr. Charles Alexander  263.0000
89                                Fortune, Miss. Mabel Helen  263.0000
439                                        Fortune, Mr. Mark  263.0000
1                                          Miss. Emily Borie  262.3750
300          Baxter, Mrs. James (Helene DeLaudeniere Chaput)  247.5208

In [ ]:
#16
survival_count = combined_df.groupby(['sex', 'survived']).size().unstack()

survival_count.rename(columns={0: 'Not Survived', 1: 'Survived'}, inplace=True)

survival_count

survived  Not Survived  Survived   2    3
sex
f                   44       180  35   76
m                  277       119  54  184

In [ ]:
#17
survival_count_by_class = combined_df.groupby(['pclass', 'survived']).size().unstack()

# Переименовываем столбцы для удобства
survival_count_by_class.rename(columns={0: 'Not Survived', 1: 'Survived'}, inplace=True)
survival_count_by_class

survived        Not Survived  Survived    2    3
pclass
1                       47.0      69.0  NaN  NaN
2                       62.0      50.0  NaN  NaN
3                      212.0      57.0  NaN  NaN
Abbott                   NaN       NaN  NaN  1.0
Abelson                  NaN       NaN  1.0  NaN
...                      ...       ...  ...  ...
Youseff                  NaN       NaN  NaN  1.0
Zabour                   NaN       NaN  NaN  1.0
de Messemaeker           NaN       NaN  NaN  1.0
de Mulder                NaN       NaN  NaN  1.0
van Billiard             NaN       NaN  NaN  1.0

[400 rows x 4 columns]